[package]
name = "fum-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fum_merkle = { path = '../merkle' }
fum_utils = { path = '../utils'}
rand = "0.8.5"
