name: "file-upload-merkle"

services:

  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  client:
    build:
      context: client
      dockerfile: Dockerfile
    
    depends_on:
      - server
  
  